### ISSUE TITLE
Upper limit to operation complexity on the GPU?

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Impero.jl#24]
@glwagner and I have struggled for a while to get complex `Oceananigans.AbstractOperations` to compile on the GPU but we're not sure if it's an Oceananigans issue or a CUDA issue.

Was just wondering if anyone using Impero.jl has encountered issues on the GPU with larger more complex operations/expressions?

X-Ref: https://github.com/CliMA/Oceananigans.jl/pull/870
X-Ref: https://github.com/CliMA/Oceananigans.jl/issues/1241

**Comment by sandreza** [comment]
Right now the current way to implement a calculation is to traverse the tree and dynamically allocate memory for each intermediate representation using CuArrays. Because of this, we haven't really run into those kind of issues, but we have run into garbage collector problems instead. Specifically, the GPU starts allocating tons of memory on the CPU

**Comment by glwagner** [comment]
Right. So when you traverse the tree, it's actually on the CPU (only the calcuation of a node is performed on GPU). Our case is different, because we compile the whole tree, so the compiler actually has to traverse the tree, somehow... (I think)...
